version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  tests:
    build: .
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm","run","test"]
            

